# Generated by Django 3.2.16 on 2023-02-24 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_chat_order_storage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chat',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Storage',
        ),
    ]
