# Generated by Django 3.2.16 on 2023-02-23 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(db_index=True, max_length=64, verbose_name='Telegram Id чата с пользователем')),
                ('dialogue_state', models.CharField(default='START', max_length=64, verbose_name='Этап диалога пользователя с ботом')),
            ],
        ),
    ]
