# Generated by Django 3.2.16 on 2023-02-24 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_bot', '0002_order_storage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='chat_id',
            field=models.CharField(max_length=64, unique=True, verbose_name='Telegram Id чата с пользователем'),
        ),
    ]
