# Generated by Django 3.2.16 on 2023-02-24 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('support_bot', '0002_order_storage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Фио')),
                ('status', models.BooleanField(default=False, verbose_name='Беру заказ')),
                ('chat', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='support_bot.chat', verbose_name='Заявка')),
                ('order', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='support_bot.order', verbose_name='Заявка')),
            ],
        ),
    ]
