# Generated by Django 3.2.16 on 2023-02-24 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('support_bot', '0003_developer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='developer',
            name='order',
        ),
        migrations.RemoveField(
            model_name='developer',
            name='status',
        ),
        migrations.AddField(
            model_name='developer',
            name='approve',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='order',
            name='developer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='support_bot.developer', verbose_name='Заявка'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='take_order',
            field=models.BooleanField(default=False, verbose_name='Беру заказ'),
        ),
        migrations.AlterField(
            model_name='developer',
            name='chat',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='support_bot.chat', verbose_name='Чат'),
        ),
    ]
