# Generated by Django 3.2.16 on 2023-02-25 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('support_bot', '0004_auto_20230224_2220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='description',
        ),
        migrations.RemoveField(
            model_name='order',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='order',
            name='take_order',
        ),
        migrations.RemoveField(
            model_name='order',
            name='title',
        ),
        migrations.RemoveField(
            model_name='order',
            name='update_at',
        ),
        migrations.AddField(
            model_name='order',
            name='finished_at',
            field=models.DateField(blank=True, null=True, verbose_name='Дата завершения'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='chat_id',
            field=models.CharField(max_length=64, unique=True, verbose_name='Telegram Id чата с пользователем'),
        ),
        migrations.AlterField(
            model_name='developer',
            name='approve',
            field=models.BooleanField(default=False, verbose_name='Разрешено ли работать'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='order',
            name='developer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='support_bot.developer', verbose_name='Кто разрабатывает'),
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiration_at', models.DateField(blank=True, null=True, verbose_name='Когда истекает срок обслуживания')),
                ('chat', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='support_bot.chat', verbose_name='Связанный чат')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='client',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='support_bot.client', verbose_name='Создан заказчиком'),
            preserve_default=False,
        ),
    ]
