# Generated by Django 3.2.16 on 2023-02-25 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support_bot', '0003_alter_chat_chat_id'),
        ('support_bot', '0004_auto_20230224_2220'),
    ]

    operations = [
    ]
