# Generated by Django 3.2.16 on 2023-02-25 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_bot', '0005_merge_0003_alter_chat_chat_id_0004_auto_20230224_2220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='developer',
            name='approve',
        ),
        migrations.AddField(
            model_name='developer',
            name='work_allowed',
            field=models.BooleanField(default=False),
        ),
    ]
